name: cloudformation-ec2

env:
  KEYPAIR_NAME: lab-keypair
  INSTANCE_TYPE: t2.micro
  SSH_SOURCE: 0.0.0.0/24
  STACK_NAME: cf-infra

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    runs-on: aws
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code from master branch
        uses: actions/checkout@v2

      # Configure AWS Credential
      - name: Deploy stack
        run: |
          if aws cloudformation describe-stacks --stack-name=$STACK_NAME > /dev/null; then
            echo "The stack already exists, update it"
            aws cloudformation update-stack --stack-name=$STACK_NAME --template-body=file://cf1/cf1.template.json --parameter=ParameterKey=InstanceType,ParameterValue=$INSTANCE_TYPE --parameter=ParameterKey=KeyName,ParameterValue=$lab-keypair --parameter=ParameterKey=SSHLocation,ParameterValue=$SSH_SOURCE
          else
            echo "The stack does not exists, create it"
            aws cloudformation create-stack --stack-name=$STACK_NAME --template-body=file://cf1/cf1.template.json --parameter=ParameterKey=InstanceType,ParameterValue=$INSTANCE_TYPE --parameter=ParameterKey=KeyName,ParameterValue=$lab-keypair --parameter=ParameterKey=SSHLocation,ParameterValue=$SSH_SOURCE
          fi
